<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class DateTimeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'text' => 'required|string',
            'publish_date' => 'required|date',
            'finished_date' => 'required|date',
            'publish_time' => 'required|date_format:H:i',
            'finished_time' => 'required|date_format:H:i',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub

    }

}
