<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'title' => 'required|string',
            'text' => 'required|string',
            'hashtag' => 'nullable|string',
            'url' => 'required|regex:/^[!-~]+$/',
            'image' => 'required|image|dimensions:width=480,height=360'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub

    }

}
